### PR TITLE
swan: Add ESDBs & up to date information.

### PR DESCRIPTION
**Pull request by PlatinumMaster**
Black 2 ESDB is now present, as is the White 2 one. American region only.
Updated information in README as well.

### CODE REVIEW

**Comment by HelloOO7** [comment]
Changes are all fine and dandy, but I think we should do something about all the generated files prior to merging since we *probably* don't need them VCd and they would clutter the Git structure a lot (seeing the 170K lines of changes was kind of wild). Not necessarily root.swandb, but the ESDBs at least we'd ideally want to have .gitattributed to binary (I guess?) and linguist-vendored. Although binary isn't exactly what these files really are. Any thoughts on that or a better solution would be appreciated.

Also wouldn't it be more practical to remove the auto-generated IDA-named symbols? I'm talking off_, sub_ and the like. Since the names are made up of absolute addresses anyway, there isn't much of where an ESDB can be of assistance with them (as they would likely change with games).

**Comment by PlatinumMaster** [comment]
I think linguist-vendoring might be a good idea for the ESDBs (since that might change a lot every commit). I was reading [this](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#generated-code); is this what you were referring to?

Also I think the IDA named symbols are fine, but we can use a newer convention to work with them outside of IDA. We really just want to make sure we can use them in any manner. Do you have a proposition for a newer convention? Or do you want to remove them?

This also just came to mind, but in the case of non-IDA we might want a tool to manage ESDB naming as well, similar to how SwanComposer generates stuff.

**Comment by HelloOO7** [comment]
I was suggesting to remove the generic symbols since they take up a lot of (imo unnecessary) space in the repo. And inasmuch as they are redundant due to their inherent ties to the binary that they originated from. If there is a reason to keep them, I'm not opposed to it, it's just that to me they seem like they do not add anything while making the DB needlessly confusing to navigate.

I didn't know linguist-generated was a thing - in that case yeah, it's a better idea than linguist-vendored. However, that only affects Github, not Git as a whole, which is why I suggested forcing it to additionally treat ESDBs as binary.

**Comment by PlatinumMaster** [comment]
Yeah I see where you're coming from. I think it might be worth keeping if people want to access certain things (for example, named arrays in `DATA`/`BSS`) personally. That way they can also do patches to the memory regions without having to relocate them to files all the time (though that would often be the best approach).

Also, treating it as binary should be fine.

**Comment by HelloOO7** [comment]
Sure. Can you amend the commit with the proper .gitattributes in place? I'm not sure if committing them separately would help since the files would already be VC'd otherwise.

I think the symbols like auto-generated string names or function stubs can be kept, it's just the ones like "off_12345" that seem pointless to me as they are pretty much just a local equivalent of (void*)(0x12345) in C with no portability benefits that the ESDBs provide.

**Comment by PlatinumMaster** [comment]
Sure, I'll get around to it soon.

**Comment by HelloOO7** [comment]
Binary seems to be unneeded as Git fares well with even large changes to the ESDB. Linguist-generated works OK. Merged.

**Pull request merged**
